[package]
name = "dream-domain-platform"
version.workspace = true
edition.workspace = true

[dependencies]
dream-core-api-types.workspace = true
dream-core-auth.workspace = true
dream-core-common.workspace = true
dream-core-db.workspace = true
async-trait.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true
