[package]
name = "dream-domain-memory"
version.workspace = true
edition.workspace = true

[dependencies]
dream-core-api-types.workspace = true
dream-core-auth.workspace = true
dream-core-common.workspace = true
dream-core-db.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx = { workspace = true, features = ["mysql"] }
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true
