ALTER TABLE one_config_sets
    ADD COLUMN alias VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN template VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN scope VARCHAR(32) NOT NULL DEFAULT 'tenant',
    ADD COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1;
