use dream_core_common::TimestampMs;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, sqlx::Type)]
#[sqlx(type_name = "TEXT", rename_all = "lowercase")]
#[serde(rename_all = "lowercase")]
pub enum UserType {
    Local,
    /// DB value is frozen at `aionpro` (existing rows); never renumber.
    #[sqlx(rename = "aionpro")]
    #[serde(rename = "aionpro")]
    DreamPro,
}

impl UserType {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Local => "local",
            Self::DreamPro => "aionpro",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, sqlx::Type)]
#[sqlx(type_name = "TEXT", rename_all = "lowercase")]
#[serde(rename_all = "lowercase")]
pub enum UserStatus {
    Active,
    Disabled,
}

impl UserStatus {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Disabled => "disabled",
        }
    }
}

/// Row mapping for the `users` table.
///
/// All fields match the SQLite column names and types exactly.
/// Optional fields correspond to nullable columns.
#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct User {
    pub id: String,
    pub user_type: UserType,
    pub external_user_id: Option<String>,
    pub username: Option<String>,
    pub email: Option<String>,
    pub password_hash: Option<String>,
    pub avatar_path: Option<String>,
    pub jwt_secret: Option<String>,
    /// Data-at-rest encryption secret, independent of `jwt_secret`.
    ///
    /// Used to derive the AES key for provider/team/mcp/channel API keys.
    /// Unlike `jwt_secret`, it is never rotated by auth/session-invalidation
    /// flows, so those flows no longer orphan encrypted data. Nullable for
    /// rows created before migration 025; backfilled at boot.
    pub data_secret: Option<String>,
    pub status: UserStatus,
    pub session_generation: i64,
    pub created_at: TimestampMs,
    pub updated_at: TimestampMs,
    pub last_login: Option<TimestampMs>,
    /// Set when the password on this account was generated by the system
    /// rather than chosen by its owner (the enterprise first-boot bootstrap).
    /// Cleared by a successful `POST /api/auth/change-password`.
    pub must_change_password: bool,
    // --- MFA (TOTP) binding, SQLite migration 055 ---
    /// AES-256-GCM ciphertext of the TOTP secret (key derived from
    /// `data_secret`). NULL = never enrolled.
    pub mfa_secret_cipher: Option<String>,
    pub mfa_enabled: bool,
    pub mfa_bound_at: Option<TimestampMs>,
    /// Admin-marked exempt from the second factor (service/API accounts).
    pub mfa_exempt: bool,
    /// Admin-marked per-user mandatory enrollment (bites in optional mode).
    pub mfa_force: bool,
    /// Last TOTP time-step that passed verification — replay guard.
    pub mfa_last_step: Option<i64>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ExternalUserProjection {
    pub username: Option<String>,
    pub email: Option<String>,
    pub avatar_path: Option<String>,
}
